
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  # 静态资源访问
  mvc:
    static-path-pattern: /**
  redis:
    host: 120.78.210.110
    port: 6379
    timeout: PT10S
    lettuce:
      pool:
        max-active: 100
        max-idle: 30
        min-idle: 1

#  mybatis
mybatis:
#  type-aliases-package: com.srb.club.dao
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
server:
  port: 8888
